CREATE TABLE Users (
    Id SERIAL PRIMARY KEY,
    Email TEXT NOT NULL UNIQUE,
    Password TEXT NOT NULL,
    FirstName TEXT NOT NULL,
    Surname TEXT NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Quiz (
    Id SERIAL PRIMARY KEY,
    Name TEXT NOT NULL,
    Type INT NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CreatedBy INT REFERENCES Users(Id)
);

CREATE TABLE Questions (
    Id SERIAL PRIMARY KEY,
    QuizId INT REFERENCES Quiz(Id),
    Index INT NOT NULL,
    Type INT NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CreatedBy INT REFERENCES Users(Id),
    QuestionText TEXT NOT NULL
);

CREATE TABLE QuestionOptions (
    Id SERIAL PRIMARY KEY,
    QuestionId INT REFERENCES Questions(Id),
    Index INT NOT NULL,
    IsCorrect BOOLEAN NOT NULL DEFAULT FALSE,
    OptionText TEXT NOT NULL,
    OptionAnswerText TEXT NOT NULL
);

